package com.paulo.independentschooldata.mappers;

import com.paulo.independentschooldata.domain.School;
import com.paulo.independentschooldata.dto.SchoolAdminDto;

import java.util.Arrays;

public class SchoolAdminMapper {

    public static SchoolAdminDto toDto(School school) {
        if (school == null) return null;

        return SchoolAdminDto.builder()
                .id(school.getId())
                .uuid(school.getUuid())
                .name(school.getName())
                .address(school.getAddress())
                .postCode(school.getPostCode())
                .regionName(school.getRegionName())
                .areaCode(school.getAreaCode())
                .phone(school.getPhone())
                .email(school.getEmail())
                .website(school.getWebsite())
                .genderProfile(school.getGenderProfile())
                .size(school.getSize())
                .religiousAffiliation(school.getReligiousAffiliation())
                .politicalAffiliation(school.getPoliticalAffiliation())
                .headName(school.getHeadName())
                .associations(school.getAssociations())
                .partnershipsLink(school.getPartnershipsLink())
                .iscRef(school.getIscRef())
                .dfeRef(school.getDfeRef())
                .mpUrl(school.getMpUrl())
                .description(school.getDescription())
                .schoolType(Arrays.stream(school.getSchoolType().split(",")).toList())
                .ethos(school.getEthos())
                .sendSchool(school.isSend())
                .sendProvision(school.getSendProvision())
                .profileUrl(school.getProfileUrl())
                .schoolImgUrl(school.getSchoolImgUrl())
                .scholarships(school.getScholarships())
                .scholarshipsDescription(school.getScholarshipsDescription())
                .scholarshipsUrl(school.getScholarshipsUrl())
                .scholarshipsAvailability(school.getScholarshipsAvailability())
                .latitude(school.getLatitude())
                .longitude(school.getLongitude())
                .boardingFees(school.getBoardingFees())
                .boardingFeeFrom(school.getBoardingFeeFrom())
                .boardingFeeTo(school.getBoardingFeeTo())
                .dayFees(school.getDayFees())
                .dayFeeFrom(school.getDayFeeFrom())
                .dayFeeTo(school.getDayFeeTo())
                .girlsInfo(school.getGirlsInfo())
                .girlsDayAgeFrom(school.getGirlsDayAgeFrom())
                .girlsDayAgeTo(school.getGirlsDayAgeTo())
                .girlsDayCount(school.getGirlsDayCount())
                .girlsBoardingAgeFrom(school.getGirlsBoardingAgeFrom())
                .girlsBoardingAgeTo(school.getGirlsBoardingAgeTo())
                .girlsBoardingCount(school.getGirlsBoardingCount())
                .girlsSixthFormCount(school.getGirlsSixthFormCount())
                .boysInfo(school.getBoysInfo())
                .boysDayAgeFrom(school.getBoysDayAgeFrom())
                .boysDayAgeTo(school.getBoysDayAgeTo())
                .boysDayCount(school.getBoysDayCount())
                .boysBoardingAgeFrom(school.getBoysBoardingAgeFrom())
                .boysBoardingAgeTo(school.getBoysBoardingAgeTo())
                .boysBoardingCount(school.getBoysBoardingCount())
                .boysSixthFormCount(school.getBoysSixthFormCount())
                .averageHousePrice(school.getAverageHousePrice())
                .featured(school.isFeatured())
                .boardingTypes(Arrays.stream(school.getBoardingTypes().split(",")).toList())
//                .stages(Arrays.stream(school.getStages().split(",")).toList())
                .schoolYears(Arrays.stream(school.getSchoolYears().split(",")).toList())
                .feeDescription(school.getFeeDescription())
                .feeSources(school.getFeeSources())
                .boardingTypeDescription(school.getBoardingTypeDescription())
                .ofstedLink(school.getOfstedLink())
                .ageRangeToFee(school.getAgeRangeToFee())
                .year13Candidates(school.getYear13Candidates())
                .percentageWithResultsAt9OrBetter(school.getPercentageWithResultsAt9OrBetter())
                .percentageWithResultsAt8OrBetter(school.getPercentageWithResultsAt8OrBetter())
                .percentageWithResultsAt7OrBetter(school.getPercentageWithResultsAt7OrBetter())
                .percentageWithResultsAt6OrBetter(school.getPercentageWithResultsAt6OrBetter())
                .percentageWithResultsAt5OrBetter(school.getPercentageWithResultsAt5OrBetter())
                .percentageWithResultsAt4OrBetter(school.getPercentageWithResultsAt4OrBetter())
                .igcse9OrBetter(school.getIgcse9OrBetter())
                .igcse8OrBetter(school.getIgcse8OrBetter())
                .igcse7OrBetter(school.getIgcse7OrBetter())
                .igcse6OrBetter(school.getIgcse6OrBetter())
                .igcse5OrBetter(school.getIgcse5OrBetter())
                .igcse4OrBetter(school.getIgcse4OrBetter())
                .igcseAOrBetter(school.getIgcseAOrBetter())
                .igcseBOrBetter(school.getIgcseBOrBetter())
                .igcseCOrBetter(school.getIgcseCOrBetter())
                .alevelAstar(school.getAlevelAstar())
                .alevelA_Astar(school.getAlevelA_Astar())
                .alevelA_B(school.getAlevelA_B())
                .alevelA_C(school.getAlevelA_C())
                .ibPoints(school.getIbPoints())
                .national5sA(school.getNational5sA())
                .national5sAB(school.getNational5sAB())
                .national5sAc(school.getNational5sAc())
                .highersA(school.getHighersA())
                .highersAB(school.getHighersAB())
                .highersAC(school.getHighersAC())
                .advancedHighersA(school.getAdvancedHighersA())
                .advancedHighersAB(school.getAdvancedHighersAB())
                .advancedHighersAC(school.getAdvancedHighersAC())
                .advancedPlacement(school.getAdvancedPlacement())
                .deleted(school.isDeleted())
                .tagLine(school.getTagLine())
                .tagLineImgUrl(school.getTagLineImgUrl())
                .feeDescriptionV3(school.getFeeDescriptionV3())
                .openDay(school.getOpenDay())
                .build();
    }

    public static School toEntity(SchoolAdminDto dto) {
        if (dto == null) return null;

        return School.builder()
                .id(dto.getId())
                .uuid(dto.getUuid())
                .name(dto.getName())
                .address(dto.getAddress())
                .postCode(dto.getPostCode())
                .regionName(dto.getRegionName())
                .areaCode(dto.getAreaCode())
                .phone(dto.getPhone())
                .email(dto.getEmail())
                .website(dto.getWebsite())
                .genderProfile(dto.getGenderProfile())
                .size(dto.getSize())
                .religiousAffiliation(dto.getReligiousAffiliation())
                .politicalAffiliation(dto.getPoliticalAffiliation())
                .headName(dto.getHeadName())
                .associations(dto.getAssociations())
                .partnershipsLink(dto.getPartnershipsLink())
                .iscRef(dto.getIscRef())
                .dfeRef(dto.getDfeRef())
                .mpUrl(dto.getMpUrl())
                .description(dto.getDescription())
                .schoolType(String.join(",", dto.getSchoolType()))
                .ethos(dto.getEthos())
                .isSend(dto.isSendSchool())
                .sendProvision(dto.getSendProvision())
                .profileUrl(dto.getProfileUrl())
                .schoolImgUrl(dto.getSchoolImgUrl())
                .scholarships(dto.getScholarships())
                .scholarshipsDescription(dto.getScholarshipsDescription())
                .scholarshipsUrl(dto.getScholarshipsUrl())
                .scholarshipsAvailability(dto.getScholarshipsAvailability())
                .latitude(dto.getLatitude())
                .longitude(dto.getLongitude())
                .boardingFees(dto.getBoardingFees())
                .boardingFeeFrom(dto.getBoardingFeeFrom())
                .boardingFeeTo(dto.getBoardingFeeTo())
                .dayFees(dto.getDayFees())
                .dayFeeFrom(dto.getDayFeeFrom())
                .dayFeeTo(dto.getDayFeeTo())
                .girlsInfo(dto.getGirlsInfo())
                .girlsDayAgeFrom(dto.getGirlsDayAgeFrom())
                .girlsDayAgeTo(dto.getGirlsDayAgeTo())
                .girlsDayCount(dto.getGirlsDayCount())
                .girlsBoardingAgeFrom(dto.getGirlsBoardingAgeFrom())
                .girlsBoardingAgeTo(dto.getGirlsBoardingAgeTo())
                .girlsBoardingCount(dto.getGirlsBoardingCount())
                .girlsSixthFormCount(dto.getGirlsSixthFormCount())
                .boysInfo(dto.getBoysInfo())
                .boysDayAgeFrom(dto.getBoysDayAgeFrom())
                .boysDayAgeTo(dto.getBoysDayAgeTo())
                .boysDayCount(dto.getBoysDayCount())
                .boysBoardingAgeFrom(dto.getBoysBoardingAgeFrom())
                .boysBoardingAgeTo(dto.getBoysBoardingAgeTo())
                .boysBoardingCount(dto.getBoysBoardingCount())
                .boysSixthFormCount(dto.getBoysSixthFormCount())
                .averageHousePrice(dto.getAverageHousePrice())
                .isFeatured(dto.isFeatured())
                .boardingTypes(String.join(",", dto.getBoardingTypes()))
//                .stages(String.join(",", dto.getStages()))
                .schoolYears(String.join(",", dto.getSchoolYears()))
                .feeDescription(dto.getFeeDescription())
                .feeSources(dto.getFeeSources())
                .boardingTypeDescription(dto.getBoardingTypeDescription())
                .ofstedLink(dto.getOfstedLink())
                .ageRangeToFee(dto.getAgeRangeToFee())
                .year13Candidates(dto.getYear13Candidates())
                .percentageWithResultsAt9OrBetter(dto.getPercentageWithResultsAt9OrBetter())
                .percentageWithResultsAt8OrBetter(dto.getPercentageWithResultsAt8OrBetter())
                .percentageWithResultsAt7OrBetter(dto.getPercentageWithResultsAt7OrBetter())
                .percentageWithResultsAt6OrBetter(dto.getPercentageWithResultsAt6OrBetter())
                .percentageWithResultsAt5OrBetter(dto.getPercentageWithResultsAt5OrBetter())
                .percentageWithResultsAt4OrBetter(dto.getPercentageWithResultsAt4OrBetter())
                .igcse9OrBetter(dto.getIgcse9OrBetter())
                .igcse8OrBetter(dto.getIgcse8OrBetter())
                .igcse7OrBetter(dto.getIgcse7OrBetter())
                .igcse6OrBetter(dto.getIgcse6OrBetter())
                .igcse5OrBetter(dto.getIgcse5OrBetter())
                .igcse4OrBetter(dto.getIgcse4OrBetter())
                .igcseAOrBetter(dto.getIgcseAOrBetter())
                .igcseBOrBetter(dto.getIgcseBOrBetter())
                .igcseCOrBetter(dto.getIgcseCOrBetter())
                .alevelAstar(dto.getAlevelAstar())
                .alevelA_Astar(dto.getAlevelA_Astar())
                .alevelA_B(dto.getAlevelA_B())
                .alevelA_C(dto.getAlevelA_C())
                .ibPoints(dto.getIbPoints())
                .national5sA(dto.getNational5sA())
                .national5sAB(dto.getNational5sAB())
                .national5sAc(dto.getNational5sAc())
                .highersA(dto.getHighersA())
                .highersAB(dto.getHighersAB())
                .highersAC(dto.getHighersAC())
                .advancedHighersA(dto.getAdvancedHighersA())
                .advancedHighersAB(dto.getAdvancedHighersAB())
                .advancedHighersAC(dto.getAdvancedHighersAC())
                .advancedPlacement(dto.getAdvancedPlacement())
                .deleted(dto.isDeleted())
                .tagLine(dto.getTagLine())
                .tagLineImgUrl(dto.getTagLineImgUrl())
                .feeDescriptionV3(dto.getFeeDescriptionV3())
                .openDay(dto.getOpenDay())
                .build();
    }
}
